environment:
  matrix:
      - APPVEYOR_BUILD_WORKER_IMAGE: WMF 4
      - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
version: 1.2.{build}
install:
- ps: |
    . ./Tools/setup.ps1
    Install-Package Configuration -Provider PowerShellGet -Minimum 1.0 -Force -ForceBootstrap
    Install-Package Pester -Provider PowerShellGet -Minimum 4.0 -Force -SkipPublisherCheck
    ./Build.ps1 -Step Clean, Update -Verbose
nuget:
  disable_publish_on_pr: true
build_script:
- ps: ./Build.ps1 -Step Build -Verbose
test_script:
- ps: ./Build.ps1 -Step Test -Verbose
deploy_script:
- ps: ./Build.ps1 -Step Package -Verbose | % { Push-AppveyorArtifact $_.FullName }
